### ISSUE TITLE
Is this component works with Force.com site without authentication ?

### ISSUE THREAD

**Issue by sudikrt** [douglascayers/sfdx-lightning-api-component#11]

**Comment by douglascayers** [comment]
Hi @sudikrt, thanks for the question and interest in this component.

I have not tested this in communities, I useit specifically for my open source project [Mass Action Scheduler](https://github.com/douglascayers-org/sfdx-mass-action-scheduler).

However, I don't think this will work in an unauthenticated session with a guest user as I don't think they have ability to invoke the APIs.
