### ISSUE TITLE
c.getVisualforceDomainURL Response 

### ISSUE THREAD

**Issue by ryanmugan** [douglascayers/sfdx-lightning-api-component#12]
Thank you for this resource! We had some issues with the c.getVisualforceDomainURL response in our Salesforce instance. Basically, it was returning some sort of re-direct script rather than the URL. 

We were able to generate the correct URL using: URL.getSalesforceBaseUrl().toExternalForm(); in the Apex class. Wondering why you opted not to go this route and through a VF page.

Thanks!

**Comment by douglascayers** [comment]
Hi @ryanmugan,

Glad you like it!

I think I was using the VF domain based on this blog post, https://developer.salesforce.com/blogs/developer-relations/2017/01/lightning-visualforce-communication.html

When I first started this project, I was not using Penpal or Postmate to manage the iframe for me, so I was trying to be secure by ensuring messages were only being passed between appropriate domains.

As I moved on with the codebase, I never had a reason to reconsider the approach with the VF domain url.

Your the first to tell me that it was sending you some redirect script though in the response. Any chance you have click-jack protection enabled for VF pages?

**Comment by ryanmugan** [comment]
Doug -

Thanks for the response. Negative on clickjack being enabled. We went through the troubleshooting steps found in your sfdx-mass-action-scheduler repo anyways though.

As written the code worked just fine in a scratch org, but once we brought it into our own we ran into issues. We do have MyDomain enabled if that makes any difference.
