### ISSUE TITLE
AuraError: Error at new Aura.externalLibraries 

### ISSUE THREAD

**Issue by SalesforceBobLightning** [douglascayers/sfdx-lightning-api-component#2]
Hi

This project is amazing! thank you!

I've got it working fine when I want to GET from

> /services/data/v45.0/tabs

But when I do this:

```
        cmp.find('lc_api').restRequest({
            'url': '/services/data/v45.0/appMenu/AppSwitcher',
            'method': 'get',
            'body': null
        }).then($A.getCallback(function (apps) {
            console.log(apps);
            cmp.set('v.apps', apps);
        })).catch($A.getCallback(function (err) {
            // handle error
            console.log(err);
        }));
```

I get this error:

> Error at new Aura.externalLibraries (https://static.lightning.force.com/cs87/auraFW/javascript/0Rz6fp7Oruhim-Qzw_AgRQ/aura_proddebug.js:26554:23) at ...

any ideas what is causing it? and how I can fix it?

**Comment by SalesforceBobLightning** [comment]
If I change the code to:

```
        cmp.find('lc_api').restRequest({
            'url': '/services/data/v45.0/appMenu/AppSwitcher',
            'method': 'get',
            'body': null
        }).then($A.getCallback(function (apps) {
            let data = JSON.parse(JSON.stringify(apps));
            console.log(data);
            cmp.set('v.apps', data.appMenuItems);
        })).catch($A.getCallback(function (err) {
            // handle error
            console.log(err);
        }));
```

It works.

But why do I need to convert to string and than back to object?

**Comment by douglascayers** [comment]
That’s a good question, I don’t know. Must be an Aura nuance. 

Maybe related, your first code example does `cmp.set('v.apps', apps)` but the second deferences the `appMenuItems` from the data response. I wonder if that makes a difference.
