### ISSUE TITLE
Timeout trying to establish connection to iframe

### ISSUE THREAD

**Issue by jesusbotella** [douglascayers/sfdx-lightning-api-component#3]
Hello!

Thank you for your awesome component, it has helped me a lot so far! :)

I am experiencing an intermittent problem when performing a request through `restRequest`, which is that a number of indetermined times it raises an error that says: `Timeout trying to establish connection to iframe`.

The code is similar to:
```js
var requestClient = component.find('lc_api').restRequest;
requestClient({
  url : '/services/data/v44.0/wave/dashboards/' + dashboardId + '/bundle',
  method: 'get'
})
```

And I'm injecting LC component in the .cmp file like:
```html
<c:lc_api aura:id="lc_api"/>
```

That request is made once several scripts are loaded, so I believe that the component has enough time to be loaded and initialized.

I don't know if I'm doing something wrong or not, but the thing is that it happens very frequently :(
I saw in DevTools network tab that the request is being made properly but the response is not returned to my component.

Am I doing something wrong? Or do I need to wait for the component initialization somehow?

Thank you very much.

**Comment by jatorre** [comment]
How often is this happening?

**Comment by douglascayers** [comment]
Hi @jesusbotella and @jatorre,

Sorry, I forgot to update the setup instructions in the last release on this repo. Please refer to https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Prerequisites#3-allow-iframing-of-visualforce-pages-with-clickjack-protection

In short, you need to whitelist your Salesforce domains for clickjack protection so the Visualforce pages can be iframed by the Lightning component. 

Please let me know if that resolves your issue. 

Thanks

**Comment by jesusbotella** [comment]
I tried yesterday and it seems like it solves the problem! I'm going to test it more but I didn't experience the error anymore.

**Comment by andrewbt** [comment]
@douglascayers Thanks! I'm working on the same project with @jesusbotella and @jatorre , and trying to box it up as an Unmanaged (Unlocked?) package as best as possible. Do you know if there's a way to include these "clickjacking Visualforce domain whitelists" in the package as XML via the Metadata API?

I found the Metadata API supports `SecuritySettings` and there are a few boolean clickjacking tags available in there (`enableClickjackNonsetupUser`, `enableClickjackNonsetupUserHeaderless`) that I believe correspond to the pre-requisites section you posted: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_securitysettings.htm However, it seems none of those settings would allow us to add the actual whitelist domains themselves that I can see.

We can pass this prerequisite whitelist domains setup on to our users after they install the package if we have to, but ideally I'd like to make this automatic when they install similar to other Metadata we have bundled in the package, like our CSP Trusted Sites settings. If you have any ideas let me know!

**Comment by douglascayers** [comment]
Hi @andrewbt,

> I found the Metadata API supports SecuritySettings... However, it seems none of those settings would allow us to add the actual whitelist domains 

My thought would have been the `SecuritySettings` is where the whitelist domains would be specified. But I'm not seeing them in the retrieved metadata either :(

This may be a gap in the Metadata API. I'll inquire internally. As workaround, I believe you'll have to add them manually.

**Comment by andrewbt** [comment]
Thanks for looking into it and verifying!

**Comment by jesusbotella** [comment]
Hi @douglascayers, here I come again :(

Setting those settings lowered the error rate that we were having, but it still happens randomly. I don't know if I'm running into some race condition or so, but the error still happens sometimes.

Do you have any clue? Thank you.

**Comment by andrewbt** [comment]
<img width="365" alt="Screen Shot 2019-05-28 at 6 31 52 PM" src="https://user-images.githubusercontent.com/2013555/58518429-33b66f80-817d-11e9-8d8e-0014ed235e75.png">

Offering up as information as I was doing some debugging on this issue, found an error in the developer console in one of the environments we are using where it was more persistent than intermittent:

`Refused to display ".../LC_APIPage" in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

Per [this Salesforce Stackexchange post](https://salesforce.stackexchange.com/questions/121260/x-frame-options-issue/230385#230385), we disabled the user's [Development mode setting](https://salesforce.stackexchange.com/questions/130666/what-is-the-significance-development-mode-on-user-record-details). This seemed to resolve the error.

**Comment by douglascayers** [comment]
Thanks for the update, @andrewbt!

@jesusbotella, any chance your user has Development Mode enabled? If so, please try [Andrew's suggestion](https://github.com/douglascayers/sfdx-lightning-api-component/issues/3#issuecomment-496725558).

Thanks

**Comment by andrewbt** [comment]
For what it's worth, I realized later on that the Development Mode setting "resolved" the error in that it changed the nature of the error from being always/constant to rare and intermittent. It seems the component _always_ errors if Development Mode is enabled. Upon later tests though we did get the error again intermittently similar to the behavior @jesusbotella originally reported. Really is too infrequent and random to establish a pattern so far unfortunately (maybe 3-5% of component loads?), does feel like a race condition or similar.

**Comment by douglascayers** [comment]
I've begun to notice intermittent timeout issues in Mass Action Scheduler, too. I'm not sure what is causing it yet.

**Comment by douglascayers** [comment]
I have a sneaky suspicion the issue may be a race condition based on what I'm reading in the penpal docs: https://github.com/Aaronius/penpal#connecttochildoptionsobject--object

I'm testing some changes that would ensure the iframe isn't loaded until after `Penpal.connectToChild` has been called, just like their example.
