### ISSUE TITLE
Are you planning on releasing a LWC version? :-)

### ISSUE THREAD

**Issue by SalesforceBobLightning** [douglascayers/sfdx-lightning-api-component#5]
Hey Doug,

I was wondering if you were planning on releasing a LWC version?

SBL

**Comment by SalesforceBobLightning** [comment]
Hey Doug,

I've been making progress converting your aura component into lwc.

But I am stuck with a TypeError error being raised on this line:

https://gist.github.com/SalesforceBobLightning/d1157163f730346ebafee4b1071d4ff4#file-api-js-L230

The console log is telling me that `child` is a `Promise` but `child.restRequest` is `undefined`

Any ideas?

**Comment by douglascayers** [comment]
Hi @SalesforceBobLightning, I'm not currently planning to convert this to LWC as I don't have need for a LWC version on my projects (yet).

The `restRequest` method is defined at https://github.com/douglascayers/sfdx-lightning-api-component/blob/master/force-app/main/pages/LC_APIPage.page#L36

So it doesn't actually exist in the JavaScript type at compile time, it's dynamically defined when making the call to `Penpal.connectToParent`
